# Generated by Django 5.1.4 on 2026-08-19 00:49

import apps.appointments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_reportfile_multi_upload"),
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="referring_partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Clínica asociada que refirió al paciente; da acceso de solo lectura a los resultados.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="partners.partner",
            ),
        ),
        migrations.AlterField(
            model_name="reportfile",
            name="file",
            field=models.FileField(
                upload_to=apps.appointments.models._report_file_path
            ),
        ),
    ]
