# Generated by Django 5.1.4 on 2026-09-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_options_alter_reportfile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='access_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
