# Generated by Django 5.1.4 on 2026-09-09 06:15

import apps.appointments.models
from django.db import migrations, models


def _backfill_stored_status(apps, schema_editor):
    """Every ReportFile row that existed before this migration was uploaded
    under the old synchronous flow, so its file is already sitting in
    storage — mark it 'stored' rather than leaving it at the new field's
    default of 'pending' (which would hide it from the patient/partner
    portals and mislabel it as still processing in the staff dashboard).

    Note: historical models used inside migrations only keep a manager's
    custom queryset filtering if that manager sets `use_in_migrations =
    True` — neither ReportFile's `objects` (SoftDeleteManager) nor
    `all_objects` do, so `apps.get_model(...).objects` here is Django's
    plain, unfiltered fallback manager (equivalent to `all_objects` on the
    real model), not the soft-delete-filtered one. That's what we want:
    backfill every row regardless of delete state.
    """
    ReportFile = apps.get_model('appointments', 'ReportFile')
    ReportFile.objects.exclude(file='').exclude(file__isnull=True).update(status='stored')


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointment_patient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='status',
            field=models.CharField(choices=[('pending', 'Procesando'), ('stored', 'Almacenado'), ('failed', 'Falló')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.appointments.models._report_file_path),
        ),
        migrations.RunPython(_backfill_stored_status, migrations.RunPython.noop),
    ]
