# Generated by Django 5.1.4 on 2026-08-26 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_email", models.CharField(blank=True, max_length=254)),
                (
                    "actor_role",
                    models.CharField(
                        choices=[
                            ("staff", "Personal"),
                            ("partner", "Clínica asociada"),
                            ("patient", "Paciente"),
                            ("public", "Público"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Consulta"),
                            ("create", "Creación"),
                            ("update", "Edición"),
                            ("delete", "Eliminación"),
                            ("upload", "Carga de archivo"),
                        ],
                        max_length=10,
                    ),
                ),
                ("object_type", models.CharField(blank=True, max_length=50)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="audit_audit_object__1f9df3_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_audit_action_766c6d_idx",
                    ),
                ],
            },
        ),
    ]
