# Generated by Django 5.1.4 on 2026-09-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view', 'Consulta'), ('create', 'Creación'), ('update', 'Edición'), ('delete', 'Eliminación'), ('upload', 'Carga de archivo'), ('email', 'Correo')], max_length=10),
        ),
    ]
